CREATE SEQUENCE IF NOT EXISTS url_seq START 1 INCREMENT 1;

CREATE TABLE IF NOT EXISTS short_links (
  id BIGSERIAL PRIMARY KEY,
  url TEXT NOT NULL ,
  hash VARCHAR(10)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_short_links_hash ON short_links (hash);

CREATE UNIQUE INDEX IF NOT EXISTS idx_url_unique ON short_links (url);